runtime: nodejs20

env_variables:
  NODE_ENV: production

handlers:
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
